version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    container_name: web
    expose:
      - 8000
    volumes:
      - static_files:/app/static
    depends_on:
      - db
    restart: unless-stopped


  db:
    image: postgres:14-alpine
    container_name: db
    environment:
      - POSTGRES_DB=shop_food
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Qwerty123
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  nginx:
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - static_files:/app/static
    depends_on:
      - web
    restart: unless-stopped

volumes:
  pgdata:
  static_files: